# Generated by Django 5.1.2 on 2024-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_client_favorites_profile_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Clinical Psychology", "Clinical Psychology"),
                    ("Counseling Psychology", "Counseling Psychology"),
                    ("Psychiatry", "Psychiatry"),
                    (
                        "Child and Adolescent Psychiatry",
                        "Child and Adolescent Psychiatry",
                    ),
                    ("Addiction Psychiatry", "Addiction Psychiatry"),
                    ("Forensic Psychiatry", "Forensic Psychiatry"),
                    ("Neuropsychology", "Neuropsychology"),
                    ("Behavioral Therapy", "Behavioral Therapy"),
                    ("Cognitive Behavioral Therapy", "Cognitive Behavioral Therapy"),
                    ("Psychoanalysis", "Psychoanalysis"),
                ],
                max_length=50,
            ),
        ),
    ]
