# Generated by Django 5.1.2 on 2024-11-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_provider_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="city",
            field=models.CharField(default="Unknown City", max_length=100),
        ),
        migrations.AddField(
            model_name="provider",
            name="line1",
            field=models.CharField(default="Unknown Address", max_length=255),
        ),
        migrations.AddField(
            model_name="provider",
            name="line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="provider",
            name="pincode",
            field=models.CharField(default="000000", max_length=10),
        ),
        migrations.AddField(
            model_name="provider",
            name="state",
            field=models.CharField(default="Unknown State", max_length=100),
        ),
    ]
