# Generated by Django 5.1.1 on 2024-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_provider_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
