# Generated by Django 5.1.2 on 2024-11-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="appointments.profile"
            ),
        ),
    ]
