# Generated by Django 5.1.2 on 2024-11-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_profile_favorites"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
